### PR TITLE
Line comments with current code indention and add a space

### PR DESCRIPTION
**Pull request by taz77**
If you use the keyboard shortcut (Mac: command (⌘)+ / ) to add a comment in IntelliJ it aligns the comment at the first column rather than respecting the current code indention. This fixes that behavior and adds a space behind the comment declaration for readability similar to Javadoc specifications.

**Reviewers**
@clockard 
@lessarderic 
@mcalcote 

ddf-checkstyle-intellij-comment-style-change

### CODE REVIEW

**Comment by coyotesqrl** [comment]
I'm not sure I see the advantage to this. The shortcut isn't designed for adding a shortcut on a blank link; it's designed for commenting out an exiting line of code. So given the following code:
```java
public class Foo {
    private String name;
    private String bar;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBar() {
        return bar;
    }

    public void setBar(String bar) {
        this.bar = bar;
    }
}
```
Your change would comment out lines thusly:
```java
public class Foo {
    private String name;
    // private String bar;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // public String getBar() {
    //     return bar;
    // }

    // public void setBar(String bar) {
    //     this.bar = bar;
    // }
}
```
as opposed to the extant formatting rules:
```java
public class Foo {
    private String name;
//    private String bar;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

//    public String getBar() {
//        return bar;
//    }

//    public void setBar(String bar) {
//        this.bar = bar;
//    }
}
```

I personally find the latter a bit clearer when viewed in a diff or text editor as a quick scan of the file will find all the comments. The difference becomes less significant when using IJ, as the code formatter provides a big enough visual difference for quick inspection.

What is the driver for this formatting change which will impact the entire DDF codebase?

**Comment by taz77** [comment]
The shortcut is for adding a comment not necessarily commenting out code - "**Comment with Line Comment**" as it says in IntelliJ. I use that shortcut to write inline comments quickly and easily.  Using your example take the following.

Starting with this code. If I were to provide inline documentation this

```
public class Foo {
    private String name;
    private String bar;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBar() {
        return bar;
    }

    public void setBar(String bar) {
        this.bar = bar;
    }
}
```

Would become this:

```
public class Foo {
    private String name;
    private String bar;
    // Return name value.
    public String getName() {
        return name;
    }
    // Set name value.
    public void setName(String name) {
        this.name = name;
    }
    // Return bar value.
    public String getBar() {
        return bar;
    }
    // Set bar value.
    public void setBar(String bar) {
        this.bar = bar;
    }
}
```

In the above example, I use the shortcut to create the comment.

Guess this honestly comes down to the preference of the developer and use of shortcuts. I put this PR up to help with code documentation, not commenting out lines of code. I am never one for committing commented out code to a repository unless I am working in my own development branch.

I do however think comments should have a space behind them before the beginning of the comment. Many of my other projects require this as a part of their coding standards and it makes for easier to read code documentation as well as providing consistency.

**Comment by clockard** [comment]
We generally try to avoid changing the format since it requires reformatting all the projects that use it. I do think this change is worth considering as part of a larger code formatter change down the road if we find more updates are needed.

**Comment by taz77** [comment]
Suggestion... Could we start an issue where we could gather changes in one location that other people might think of for formatting?

**Comment by coyotesqrl** [comment]
We could open a running Jira ticket or (maybe better as it won't sit in the backlog) create a Confluence page to track these.

It would also give us a place where we could discuss and vote on formatting changes so consensus is reached before making them.

**Comment by taz77** [comment]
Sounds good.

**Comment by lessarderic** [comment]
@taz77, now that we're using Google Java Formatter, is this PR still needed?

**Pull request closed without merging**
