### PR TITLE
DDF-1671 Updates Intellij code formatter to handle fluent APIs.

### PR DESCRIPTION
**Pull request by coyotesqrl**
Adds the default marker tags for turning formatting off/on in order to allow blocks of code to be marked to be ignored by the code formatter. This should be used very sparingly.

```java
// @formatter:off
System.out.println(     "if I were stupid and wanted spaces"   );
// @formatter.on
```

@codice/green

### CODE REVIEW

**Comment by ryeats** [comment]
:+1:

**Comment by roelens8** [comment]
:+1:

**Comment by coyotesqrl** [comment]
@shaundmorris Green's going to take a quick look at this. It's a small enhancement that we need in order to support user-specified formatting in some places (notably RestAssured fluent calls).

**Comment by tbatie** [comment]
:+1:

**Comment by coyotesqrl** [comment]
@shaundmorris When you get a chance, could you please merge this?

**Comment by rzwiefel** [comment]
test @codice/green  test

**Pull request merged**
