### PR TITLE
DDF-2263 Update the code formatter so it does not collapse java.awt.* and javax.swing.* imports.

### PR DESCRIPTION
**Pull request by coyotesqrl**
@lessarderic @rzwiefel @tbatie @shaundmorris

### CODE REVIEW

**Comment by lessarderic** [comment]
Getting strange results when formatting `TestCatalog` with the new configuration.

IntelliJ also shows two `Code Style` options when importing instead of one like it used to. Looks like this new jar contains XML related configuration so I wonder if this could be related.

One more thing. Do you think we should include the formatting on/off toggles (`// formatting:on`, `// formatting:off`) in our standard formatter since they are being used in our itest code?

**Comment by lessarderic** [comment]
Re-ran the formatter on `TestCatalog` after making some manual line "unwrapping" and things look ok now so you can ignore my first comment.

**Comment by bcwaters** [comment]
I've hero'd this.

I ran the code formatter on some code which contained at least 5 imports from java.awt and javax.swing to confirm these imports are no longer collapsed.  I also ran the formatter on some existing code to confirm code is still being formatted as expected.

**Comment by coyotesqrl** [comment]
@shaundmorris Are we good to merge this change?

**Comment by lessarderic** [comment]
@coyotesqrl, any thoughts/comments on my `Code Style` and formatting on/off questions above?

**Comment by coyotesqrl** [comment]
The on/off toggles we're using are the IJ defaults, so they should be supported in this formatter with no problems. And as they're just comments, I can't see got checkstyle would notice or care about them.

**Comment by shaundmorris** [comment]
👍 I don't think this requires a new release of ddf-support. Probably worth a developers forum post as well.

**Pull request merged**
