### PR TITLE
DDF-1183: Update to include support files to run findbugs.

### PR DESCRIPTION
**Pull request by ckurata**
Update ddf-support files to specify the findbugs exclusion file, used by the parent POM file.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-support/3)

### CODE REVIEW

**Comment by ckurata** [comment]
@oconnormi, @jckilmer, @lessarderic

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by lessarderic** [comment]
Reviewed files:
- pom.xml @ r1
- support-findbugs/pom.xml @ r1
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by jckilmer** [comment]
Reviewed files:
- pom.xml @ r1
- support-findbugs/pom.xml @ r1
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by lessarderic** [comment]
Before you commit, can you replace all the tabs with 4 spaces?

Otherwise looks good!

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by ckurata** [comment]
The XML files have been committed with the formatting suggestion.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by lessarderic** [comment]
I still see tabs in the new version (red >> in Reviewable). Are you sure you committed the files?

---





<sup>**[pom.xml, line 24 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-support/3#-JoVzwGfG8A4NOt-hSh_)** ([raw file](https://github.com/codice/ddf-support/blob/e1c0432ba279dac2764aecc99b8f08f946a01c9d/pom.xml#L24)):</sup>
Here's an example at beginning of the 5 previous lines.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by oconnormi** [comment]
<sup>**[pom.xml, line 24 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-support/3#-JoVzwGfG8A4NOt-hSh_)** ([raw file](https://github.com/codice/ddf-support/blob/e1c0432ba279dac2764aecc99b8f08f946a01c9d/pom.xml#L24)):</sup>
@ckurata, If using vim check in your `~/.vimrc` it should have `:set expandtab` as well as a line like `set tabstop=4`. If it has a lower number for tabstop you can increase it and then run `:retab` in the file and it should resolve anything that was using tabs instead of spaces

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by ckurata** [comment]
The XML files have been committed with the formatting suggestion.

---





<sup>**[pom.xml, line 24 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-support/3#-JoVzwGfG8A4NOt-hSh_)** ([raw file](https://github.com/codice/ddf-support/blob/e1c0432ba279dac2764aecc99b8f08f946a01c9d/pom.xml#L24)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by ckurata** [comment]
The xml files have been re-tabbed.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by oconnormi** [comment]
Looks good to me

---

Reviewed files:
- pom.xml @ r3
- support-findbugs/pom.xml @ r3
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by lessarderic** [comment]
Ship it!

---

Reviewed files:
- pom.xml @ r3
- support-findbugs/pom.xml @ r3
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by jckilmer** [comment]
Reviewed files:
- pom.xml @ r3
- support-findbugs/pom.xml @ r3
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Comment by shaundmorris** [comment]
Reviewed files:
- pom.xml @ r3
- support-findbugs/pom.xml @ r3
- support-findbugs/src/main/resources/findbugs-exclude.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/3)

**Pull request merged**
