### PR TITLE
Script to add JaCoCo code coverage configuration to pom files

### PR DESCRIPTION
**Pull request by lessarderic**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-support/2)

### CODE REVIEW

**Comment by shaundmorris** [comment]
<sup>**[support-jacoco/src/main/groovy/updatePomFiles.groovy, line 40 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-support/2#-JndirtKZHNoda9pxpeN)** ([raw file](https://github.com/codice/ddf-support/blob/79979609b284eb44e85c373d0b8ea7671bfe0842/support-jacoco/src/main/groovy/updatePomFiles.groovy#L40)):</sup>
Thanks for including this. Seems like a README is overkill.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/2)

**Comment by shaundmorris** [comment]
Reviewed files:
- pom.xml @ r1
- support-jacoco/pom.xml @ r1
- support-jacoco/src/main/groovy/updatePomFiles.groovy @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/2)

**Comment by shaundmorris** [comment]
There was a bit of discussion as to why we would need a script to add to pom files, but there is a customizable part with the percentages for each project that we would want to have. No -1's so planning on merging it for reference since it most likely shouldn't need any additional maintenance.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/2)

**Comment by lessarderic** [comment]
Actually, we want to keep the script. We'll need to change it a little so that it can update the numbers moving forward. We should have a ticket every sprint or 2 to re-run and update the coverage numbers. That should help bring them up over time.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/2)

**Comment by lessarderic** [comment]
Created https://jira.di2e.net/browse/DIB-2497 for this.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-support/2)

**Pull request merged**
