### PR TITLE
DDF-1671 Updates Intellij code formatter to handle fluent APIs.

### PR DESCRIPTION
**Pull request by coyotesqrl**
##### Description
For Java codestyle:
* Wrapping and Braces > Assignment Statement -> Set to 'wrap if long'
* Wrapping and Braces > chained method calls > Set to 'wrap always'
* Wrapping and Braces > Method Call arguments -> Chop down if long & Take priority over call chain wrapping`

Please note that there are some subtle differences between the way Intellij formats when setting the chained method calls to always wrap. It means that single method invocations won't be wrapped to the next line when the right margin is exceeded. The first bullet point above, making assignment statements wrap if long, is, I believe, a compromise that will prevent us from exceeding the right margin much more than we used to but still give us well-formatted chained methods.

##### Reviewers
@jckilmer
@rzwiefel
@roelens8 (hero)
@ryeats
@pklinef 

##### Before and After
Following are two copies of a sample Java file formatted first with the old formatting rules and then with the new ones.

###### old rules
```java
/**
 * Copyright (c) Codice Foundation
 * <p>
 * This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or any later version.
 * <p>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details. A copy of the GNU Lesser General Public License
 * is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package ddf.catalog;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

/**
 * This is class-level javadoc.
 * <p>
 * This is a sample class to demonstrate before and after formatting with the changes made for DDF-1671.
 */
public class FormattingExample {
    private final String longString = "This is a long string, one that stretches beyond the 100-character right margin";

    private String prettyShort = "Not so long";

    private long millisFromLongSum =
            TimeUnit.DAYS.toMillis(3) + TimeUnit.HOURS.toMicros(7) + TimeUnit.HOURS.toSeconds(12);

    private static final String LONG_CONST = "This is a long constant, one that stretches beyond the 100-character right margin";

    private static final String SHORT_CONST = "I'm short";

    private static final long LONG_NEST = getLongFromLong(
            getLongFromLong(getLongFromLong(getLongFromLong(2))));

    private static final long SHORT_CHAIN = new ChainTester(2).add(2).add(2).add(2).getVal();

    private static final long LONG_CHAIN = new ChainTester(2).add(2).add(2).add(2).add(2).add(2)
            .add(2).getVal();

    private long nestMethods() {
        return getLongFromLong(getLongFromLong(
                getLongFromLong(getLongFromLong(getLongFromLong(getLongFromLong(2))))));
    }

    private long chainMethods() {
        return new ChainTester(2).add(2).add(2).add(2).add(2).add(2).add(2).getVal();
    }

    private void fluent() {
        List<String> strings = Arrays
                .asList("java8", "is", "much", "closer", "to", "a", "functional", "paradigm")
                .stream().filter(s -> s.startsWith("i")).collect(Collectors.toList());
    }

    private void manyParams() {
        takesManyParams("hello", "world", LONG_CONST, SHORT_CONST,
                "This string is a bit longer than the others", "This one too", "goodnight",
                "columbus");
    }

    private void takesManyParams(String a, String b, String c, String d, String e, String f,
            String g, String h) {
        // do nothing
    }

    static long getLongFromLong(long l) {
        return l + 2;
    }

    static class ChainTester {
        private long val;

        public ChainTester(long val) {
            this.val = val;
        }

        ChainTester add(long l) {
            val += l;
            return this;
        }

        public long getVal() {
            return val;
        }
    }
}
```

###### new rules
```java
/**
 * Copyright (c) Codice Foundation
 * <p>
 * This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or any later version.
 * <p>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details. A copy of the GNU Lesser General Public License
 * is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package ddf.catalog;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

/**
 * This is class-level javadoc.
 * <p>
 * This is a sample class to demonstrate before and after formatting with the changes made for DDF-1671.
 */
public class FormattingExample {
    private final String longString =
            "This is a long string, one that stretches beyond the 100-character right margin";

    private String prettyShort = "Not so long";

    private long millisFromLongSum =
            TimeUnit.DAYS.toMillis(3) + TimeUnit.HOURS.toMicros(7) + TimeUnit.HOURS.toSeconds(12);

    private static final String LONG_CONST =
            "This is a long constant, one that stretches beyond the 100-character right margin";

    private static final String SHORT_CONST = "I'm short";

    private static final long LONG_NEST = getLongFromLong(getLongFromLong(getLongFromLong(
            getLongFromLong(2))));

    private static final long SHORT_CHAIN = new ChainTester(2).add(2)
            .add(2)
            .add(2)
            .getVal();

    private static final long LONG_CHAIN = new ChainTester(2).add(2)
            .add(2)
            .add(2)
            .add(2)
            .add(2)
            .add(2)
            .getVal();

    private long nestMethods() {
        return getLongFromLong(getLongFromLong(getLongFromLong(getLongFromLong(getLongFromLong(
                getLongFromLong(2))))));
    }

    private long chainMethods() {
        return new ChainTester(2).add(2)
                .add(2)
                .add(2)
                .add(2)
                .add(2)
                .add(2)
                .getVal();
    }

    private void fluent() {
        List<String> strings = Arrays.asList("java8",
                "is",
                "much",
                "closer",
                "to",
                "a",
                "functional",
                "paradigm")
                .stream()
                .filter(s -> s.startsWith("i"))
                .collect(Collectors.toList());
    }

    private void manyParams() {
        takesManyParams("hello",
                "world",
                LONG_CONST,
                SHORT_CONST,
                "This string is a bit longer than the others",
                "This one too",
                "goodnight",
                "columbus");
    }

    private void takesManyParams(String a, String b, String c, String d, String e, String f,
            String g, String h) {
        // do nothing
    }

    static long getLongFromLong(long l) {
        return l + 2;
    }

    static class ChainTester {
        private long val;

        public ChainTester(long val) {
            this.val = val;
        }

        ChainTester add(long l) {
            val += l;
            return this;
        }

        public long getVal() {
            return val;
        }
    }
}
```

### CODE REVIEW

**Comment by roelens8** [comment]
Built successfully. :+1:

**Comment by coyotesqrl** [comment]
@roelens8 To hero, I would suggest comparing the before and after formatting changes and confirming that they do as expected and make no other, unwanted changes. Also, confirmation that only the settings that were specified as changed actually were changed.

**Comment by pklinef** [comment]
How big of an impact is there on the ddf repo if these new rules are applied?

**Comment by coyotesqrl** [comment]
Not sure. I'll test that out now.

**Comment by coyotesqrl** [comment]
It's difficult to determine the impact. 1539 files were updated in the DDF repo when I reformated just now, but many of those were updates to the `<p>` tags in copyright blocks and javadocs.

**Comment by ryeats** [comment]
The wrapping seems weird on this one but I think I can live with that since everything else looks great. :+1: 
```
private long millisFromLongSum =
            TimeUnit.DAYS.toMillis(3) + TimeUnit.HOURS.toMicros(7) + TimeUnit.HOURS.toSeconds(12);
```

**Comment by brendan-hofmann** [comment]
Yet another question is do we plan to reformat the codebase with this new formatter? I'm ok with the answer being no, as long as we're all aware that it could make everyone else's pull requests noisier if they're using the formatter. (which they should be!)

**Comment by coyotesqrl** [comment]
I'm of two minds on that. I ran a quick check over the code base and found
a *lot* of files that would be reformatted; however, many of those were
files that were out of date to begin with and the changes consisted of
updating `<p>` tags.

We can certainly run the formatter once after it's updated as long as we'd
be okay with a fairly large commit of no actual content.

**Comment by brendan-hofmann** [comment]
There is precedent. ;) We already did one massive reformatting commit.

My inclination is for consistency up front as much as possible. I'd rather eat the formatting noise up front and all at once.
On Nov 30, 2015, at 09:41, R.A. Porter <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm of two minds on that. I ran a quick check over the code base and found
a *lot* of files that would be reformatted; however, many of those were
files that were out of date to begin with and the changes consisted of
updating `<p>` tags.

We can certainly run the formatter once after it's updated as long as we'd
be okay with a fairly large commit of no actual content.

**Comment by ahoffer** [comment]
I like the changes. I vote to reformat all the code.

**Pull request merged**
